source 'https://rubygems.org'

ruby '~> 3.1'

gem 'sinatra', '~> 3.0'
gem 'sinatra-contrib', '~> 3.0'
gem 'rack-cors', '~> 2.0'
gem 'jwt', '~> 2.8'
gem 'httparty', '~> 0.21'
gem 'dotenv', '~> 3.0'
gem 'puma', '~> 6.0'

group :test do
  gem 'rspec', '~> 3.13'
  gem 'rack-test', '~> 2.1'
  gem 'webmock', '~> 3.23'
end
